baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
author = "Wade Armstrong"
canonifyurls = true
paginate = 3
# Enable syntax highlighting
# comment or delete lines 11 ~ 14
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses=true
pygmentsOptions = "linenos=table"